openapi: '3.0.3'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
    description: all pets
  - name: cats
    description: cats only
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
              examples:
                allDogs:
                  value:
                    - id: 3140821
                      name: AN_CMY51
                      petType: Dog
                      packSize: 4
                    - id: 12879062
                      name: AN_QKT85
                      petType: Dog
                      packSize: 1
                      tag: et cupidatat dolor id minim
                    - id: 2577457
                      name: AN_JTG08
                      petType: Dog
                      packSize: 1
                      tag: minim anim
                allCats:
                  value:
                    - id: 6701
                      name: AN_LXY01
                      huntingSkill: clueless
                      tag: fugiat
                      petType: Cat
                    - id: 6702
                      name: AN_LYX02
                      huntingSkill: aggressive
                      petType: Cat
                      tag: ea
                    - id: 20859021
                      name: AN_WNP0
                      huntingSkill: adventurous
                      tag: nisi
                      petType: Cat
                    - id: 21197073
                      name: AN_ZRD91
                      petType: Cat
                      huntingSkill: clueless
                      tag: quis
                mixed:
                  value:
                    - id: 3140821
                      name: AN_CMY51
                      petType: Dog
                      packSize: 4
                    - id: 6701
                      name: AN_LXY01
                      huntingSkill: clueless
                      tag: fugiat
                      petType: Cat
                    - id: 12879062
                      name: AN_QKT85
                      petType: Dog
                      packSize: 1
                      tag: et cupidatat dolor id minim
                    - id: 2577457
                      name: AN_JTG08
                      petType: Dog
                      packSize: 1
                      tag: minim anim
                    - id: 6702
                      name: AN_LYX02
                      huntingSkill: aggressive
                      petType: Cat
                      tag: ea
                    - id: 12
                      name: wrongName
                      petType: Cat
                      packSize: 1
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Created wit response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OneOfPet'
              examples:
                cat:
                  value:
                    id: 001
                    name: AN_BBB02
                    huntingSkill: aggressive
                    petType: Cat
                    tag: just created
                dog:
                  value:
                    id: 001
                    name: wrongName
                    petType: Dog
                    packSize: 4
                    tag: just created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OneOfPet'
              examples:
                anexample:
                  value:
                    id: 007
                    name: AN_EXM07
                    huntingSkill: lazy
                    petType: Cat
                    tag: mathod example 007

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cats/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showCatById
      tags:
        - cats
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              example:
                id: 001
                name: AN_EXM_01
                huntingSkill: aggressive
                petType: Cat
                tag: mathod example
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          readOnly: true
        name:
          type: string
          pattern: "AN_[A-Z]{3}\\d{1,3}"
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/OneOfPet'
    OneOfPet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: petType

    Cat: ## "Cat" will be used as the discriminator value
      description: A representation of a cat
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            huntingSkill:
              type: string
              description: The measured skill for hunting
              enum:
                - clueless
                - lazy
                - adventurous
                - aggressive
            petType:
              type: string
              enum: ['Cat']
            kind:
              type: string
              x-faker: animal.cat
          required:
            - huntingSkill
            - petType

      example:
        id: 002
        name: AN_EXM_02
        huntingSkill: aggressive
        petType: Cat
        tag: type example
    Dog: ## "Dog" will be used as the discriminator value
      description: A representation of a dog
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            packSize:
              type: integer
              format: int32
              description: the size of the pack the dog is from
              default: 0
              minimum: 0
            petType:
              type: string
              enum: ['Dog']
          required:
            - packSize
            - petType
      example:
        id: 1111
        name: AN_CMY11
        petType: Dog
        tag: dog dog dog
        packSize: 4
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
